workInProgress: true
credits:
#  - package:
#      name: Nunjucks
#      url: https://mozilla.github.io/nunjucks/
#      license: '[Copyright (c) 2012-2015, James Long, BSD License](https://github.com/mozilla/nunjucks/blob/master/LICENSE)'
#    author:
#      name: James Long
#      url: https://github.com/mozilla/
copyright:
  year: <%- author.year %>
  author:
    name: <%- author.name %>
    url: <%- author.url %>

example: |
  an example...

